### ISSUE TITLE
integrate_ode_bdf causing sampler to crash

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/math#1114]
## Description
I tried re-running an older model (used in my dissertation, with, IIRC, stan 2.16,) in the newest version of rstan, and it crashes. After investigating, it seems the stiff solver is no longer working.

The model below (adapted nearly directly from the manual,) can be run as-is in rstan. It runs successfully (when modified) using the non-stiff solver, integrate_ode_rk45, but crashes R (run as-is,) when using integrate_ode_bdf.

## Example

```
series = seq(0.1,9.2,1)

data_ode=list(T = 10,
y0 = c(1,0),
t0=0,
ts=series
)

scode_bdf <- "
functions {
real[] sho(real t,
real[] y,
real[] theta,
real[] x_r,
int[] x_i) {
real dydt[2];
dydt[1] = y[2];
dydt[2] = -y[1] - theta[1] * y[2];
return dydt;
}
}
data {
int<lower=1> T;
real y0[2];
real t0;
real ts[T];
}

transformed data {
real x_r[0];
int x_i[0];
}
parameters{
real theta[1];
}
model {
theta ~ normal(0.15,0.1);
}
generated quantities {
real y_hat[T,2] = integrate_ode_bdf(sho, y0, t0, ts, theta, x_r, x_i);
// add measurement error
for (t in 1:T) {
y_hat[t, 1] += normal_rng(0, 0.1);
y_hat[t, 2] += normal_rng(0, 0.1);
}
}
"

fit_bdf <- stan(model_code = scode_bdf, data=data_ode, iter = 10000, verbose = FALSE)
```

## Expected Output

Not crashing.

#### Current Version:
v2.18.1 (rstan v2.18.2)

**Comment by wds15** [comment]
Odd with this setup:

```
other attached packages:
[1] rstan_2.18.2         StanHeaders_2.18.0-1 ggplot2_3.1.0       
[4] VGAM_1.0-6           RBesT_1.3-7          Rcpp_1.0.0          
```

it works just fine... I will bump the StanHeaders version

**Comment by davidmanheim** [comment]
Also note: I'm running R 3.5.2 and Rtools 3.5, on Windows 10.

**Comment by wds15** [comment]
Hmm.. I just tried with cmdstan 2.18.1 on MacOS High Sierra. Works just fine.

Would it be possible for you to try cmdstan on your system with this model? With cmdstan we can be relatively sure that indeed its a Stan problem on this platform.

**Comment by davidmanheim** [comment]
@wds15 - in case it wasn't clear, further information on this is awaiting a solution for a different, seemingly unrelated, issue: https://github.com/stan-dev/cmdstan/issues/673

**Comment by bgoodri** [comment]
Here is what might be known about this bug. Running it under GDB with optimization yields this not-so-helpful backtrace
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffbf954860 in msvcrt!memmove () from C:\WINDOWS\System32\msvcrt.dll
(gdb) bt
#0  0x00007fffbf954860 in msvcrt!memmove ()
   from C:\WINDOWS\System32\msvcrt.dll
#1  0x000000006b702e83 in file3a24183231a!_ZN4stan4math15cvodes_ode_dataIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace13sho_functor__EddE6cv_rhsEdP17_generic_N_VectorS6_Pv ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#2  0x0000000012cadec7 in StanHeaders!CVode ()
   from C:\Users\Stan\Documents\R\win-library\3.5\StanHeaders\libs\x64\StanHeaders.dll
#3  0x000000006b704671 in file3a24183231a!_ZN4stan4math17cvodes_integratorILi2EE9integrateIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace13sho_functor__EddEESt6vectorIS6_INS_11return_typeIT0_T1_ddddE4typeESaISB_EESaISD_EERKT_RKS6_IS8_SaIS8_EEdRKS6_IdSaIdEERKS6_IS9_SaIS9_EESQ_RKS6_IiSaIiEEPSoddl ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#4  0x000000006b76ceca in file3a24183231a!_ZNK60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b411write_arrayIN5boost6random23additive_combine_engineINS3_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS5_IjLj40692ELj0ELj2147483399EEEEEEEvRT_RSt6vectorIdSaIdEERSB_IiSaIiEESE_bbPSo ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#5  0x000000006b71c3f6 in file3a24183231a!_ZN4stan8services4util11mcmc_writer19write_sample_paramsIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EN5boost6random23additive_combine_engineINS7_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS9_IjLj40692ELj0ELj2147483399EEEEEEEvRT0_RNS_4mcmc6sampleERNSF_9base_mcmcERT_
    () from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#6  0x000000006b71d1b3 in file3a24183231a!_ZN4stan8services4util20generate_transitionsIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EN5boost6random23additive_combine_engineINS6_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS8_IjLj40692ELj0ELj2147483399EEEEEEEvRNS_4mcmc9base_mcmcEiiiiibbRNS1_11mcmc_writerERNSC_6sampleERT_RT0_RNS_9callbacks9interruptERNSN_6loggerE ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#7  0x000000006b71da23 in file3a24183231a!_ZN4stan8services4util20run_adaptive_samplerINS_4mcmc17adapt_diag_e_nutsIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EN5boost6random23additive_combine_engineINS8_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENSA_IjLj40692ELj0ELj2147483399EEEEEEES6_SD_EEvRT_RT0_RSt6vectorIdSaIdEEiiiibRT1_RNS_9callbacks9interruptERNSP_6loggerERNSP_6writerESV_ ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#8  0x000000006b724122 in file3a24183231a!_ZN4stan8services6sample21hmc_nuts_diag_e_adaptIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EEEiRT_RNS_2io11var_contextES9_jjdiiibiddiddddjjjRNS_9callbacks9interruptERNSA_6loggerERNSA_6writerESG_SG_ ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#9  0x000000006b6ca79b in file3a24183231a!_rcpp_module_boot_stan_fit4model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_mod ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#10 0x000000006b750444 in file3a24183231a!_ZN5rstan8stan_fitIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EN5boost6random23additive_combine_engineINS4_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS6_IjLj40692ELj0ELj2147483399EEEEEE12call_samplerEP7SEXPREC ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#11 0x000000006b6f3eac in file3a24183231a!_ZN4Rcpp6class_IN5rstan8stan_fitIN60model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace50model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4EN5boost6random23additive_combine_engineINS6_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS8_IjLj40692ELj0ELj2147483399EEEEEEEE14invoke_notvoidEP7SEXPRECSF_PSF_i ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#12 0x000000006abc885e in CppMethod__invoke_notvoid(SEXPREC*) ()
   from C:\Users\Stan\Documents\R\win-library\3.5\Rcpp\libs\x64\Rcpp.dll
#13 0x000000006c7a4a52 in Rf_NewFrameConfirm ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#14 0x000000006c80010c in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#15 0x000000006c802e76 in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#16 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#17 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#18 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#19 0x000000006c7ffd02 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#20 0x000000006c8003dc in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#21 0x000000006c7fdf2c in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#22 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#23 0x000000006c8003dc in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#24 0x000000006c7fdf2c in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#25 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#26 0x000000006c8003dc in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#27 0x000000006c7fdf2c in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#28 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#29 0x000000006c8003dc in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#30 0x000000006c7fdf2c in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#31 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#32 0x000000006c8003dc in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#33 0x000000006c7fdf2c in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#34 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#35 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#36 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#37 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#38 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#39 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#40 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#41 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#42 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#43 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#44 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#45 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#46 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#47 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#48 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#49 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#50 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#51 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#52 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#53 0x000000006c7ffd02 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#54 0x000000006c803f5e in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#55 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#56 0x000000006c802e76 in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#57 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#58 0x000000006c806749 in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#59 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#60 0x000000006c802e76 in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#61 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#62 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#63 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#64 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#65 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#66 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#67 0x000000006c80265e in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#68 0x0000000064a42cf2 in methods!R_dispatchGeneric ()
   from C:\Program Files\R\R-3.5.1\library\methods\libs\x64\methods.dll
#69 0x000000006c83b972 in R_set_standardGeneric_ptr ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#70 0x000000006c7f7b5d in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#71 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#72 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#73 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#74 0x000000006c7f531a in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#75 0x000000006c7ffd41 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#76 0x000000006c801354 in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#77 0x000000006c8023e2 in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#78 0x000000006c7ffd02 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#79 0x000000006c803f5e in R_execMethod ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#80 0x000000006c7fff06 in Rf_eval () from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#81 0x000000006c82618c in Rf_ReplIteration ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#82 0x000000006c826581 in Rf_ReplIteration ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#83 0x000000006c826612 in run_Rmainloop ()
   from C:\PROGRA~1\R\R-35~1.1\bin\x64\R.dll
#84 0x00000000004016cf in ?? ()
#85 0x000000000040155a in ?? ()
#86 0x00000000004013e8 in ?? ()
#87 0x000000000040151b in ?? ()
#88 0x00007fffbfa381f4 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#89 0x00007fffc21ba251 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#90 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```
However, Windows can no longer compile Stan programs without optimization, so we cannot get human-readable symbol names. A rough translation of the above is:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffbf954860 in msvcrt!memmove () from C:\WINDOWS\System32\msvcrt.dll
(gdb) bt
#0  0x00007fffbf954860 in msvcrt!memmove ()
   from C:\WINDOWS\System32\msvcrt.dll
#1  0x000000006b702e83 in file3a24183231a! 
stan::math::cvodes_ode_data<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::sho_functor__, double, double>
::cv_rhs(double, _generic_N_Vector*, _generic_N_Vector*, void*) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#2  0x0000000012cadec7 in StanHeaders!CVode ()
   from C:\Users\Stan\Documents\R\win-library\3.5\StanHeaders\libs\x64\StanHeaders.dll
#3  0x000000006b704671 in file3a24183231a! 
std::vector<std::vector<stan::return_type<double, double, double, double, double, double>::type, 
std::allocator<stan::return_type<double, double, double, double, double, double>::type> >, 
std::allocator<std::vector<stan::return_type<double, double, double, double, double, double>::type, 
std::allocator<stan::return_type<double, double, double, double, double, double>::type> > > > 
stan::math::cvodes_integrator<2>::integrate<
model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::sho_functor__, double, double>
(model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::sho_functor__ const&, 
std::vector<double, std::allocator<double> > const&, double, std::vector<double, std::allocator<double> > 
const&, std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > 
const&, std::vector<int, std::allocator<int> > const&, std::basic_ostream<char, std::char_traits<char> >*, 
double, double, long) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#4  0x000000006b76ceca in file3a24183231a! void model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4
::write_array<boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >(boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >&, std::vector<double, std::allocator<double> >&, 
std::vector<int, std::allocator<int> >&, std::vector<double, std::allocator<double> >&, bool, bool, std::basic_ostream<char, std::char_traits<char> >*) const ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#5  0x000000006b71c3f6 in file3a24183231a! void stan::services::util::mcmc_writer::write_sample_params<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >(boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >&, stan::mcmc::sample&, stan::mcmc::base_mcmc&, 
model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4&)
    () from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#6  0x000000006b71d1b3 in file3a24183231a! void stan::services::util::generate_transitions<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > 
>(stan::mcmc::base_mcmc&, int, int, int, int, int, bool, bool, stan::services::util::mcmc_writer&, stan::mcmc::sample&, model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4&, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >&, stan::callbacks::interrupt&, stan::callbacks::logger&) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#7  0x000000006b71da23 in file3a24183231a! void stan::services::util::run_adaptive_sampler<stan::mcmc::adapt_diag_e_nuts<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >, 
model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >(stan::mcmc::adapt_diag_e_nuts<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >&, 
model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4&, std::vector<double, std::allocator<double> >&, int, int, int, int, bool, 
boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, 
boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >&, stan::callbacks::interrupt&, stan::callbacks::logger&, stan::callbacks::writer&, stan::callbacks::writer&) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#8  0x000000006b724122 in file3a24183231a! int stan::services::sample::hmc_nuts_diag_e_adapt<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4>
(model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4&, stan::io::var_context&, stan::io::var_context&, unsigned int, unsigned int, double, int, int, int, bool, int, double, double, int, double, double, double, double, unsigned int, unsigned int, unsigned int, stan::callbacks::interrupt&, stan::callbacks::logger&, stan::callbacks::writer&, stan::callbacks::writer&, stan::callbacks::writer&)
 ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#9  0x000000006b6ca79b in file3a24183231a!_rcpp_module_boot_stan_fit4model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_mod ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#10 0x000000006b750444 in file3a24183231a! rstan::stan_fit<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::call_sampler(SEXPREC*) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#11 0x000000006b6f3eac in file3a24183231a! Rcpp::class_<rstan::stan_fit<model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4_namespace::model3a2420fb4a1c_c615ed0ce1bcb2ba6161175a688a90b4, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > > >::invoke_notvoid(SEXPREC*, SEXPREC*, SEXPREC**, int) ()
   from C:\Users\Stan\AppData\Local\Temp\RtmpKMRKyY\file3a24183231a.dll
#12 0x000000006abc885e in CppMethod__invoke_notvoid(SEXPREC*) ()
   from C:\Users\Stan\Documents\R\win-library\3.5\Rcpp\libs\x64\Rcpp.dll
...
```
But I still can't take anything away from that other than it crashed.

**Comment by yizhang-cae** [comment]
Looks like an access issue of SUNDIALS N_vector. But with above information it's not reproducible. Does it crash on every run or just some runs?

**Comment by bgoodri** [comment]
It is not completely reproducible but I can always trigger it on the
Windows machine in my office if I run the model enough times.

**Comment by yizhang-cae** [comment]
So it depends on random seed maybe? Run with the failure seed may improve the reproducibility.

**Comment by wds15** [comment]
Can u rerun now with Stan 2.19 which has sundials upgraded to 4.1.0. Hopefully this fixes the issue.

**Comment by davidmanheim** [comment]
Success!

Now all I need is RStan 2.19 to be released so I can get back to the original problem...

**Comment by wds15** [comment]
Great! I like if problems just go away like that.

**Comment by bbbales2** [comment]
@davidmanheim is this problem solved?

**Comment by davidmanheim** [comment]
I will check this when I can and update - I've been fairly busy.

**Comment by davidmanheim** [comment]
@bbbales2 - The computer I was using at the time had the screen break, and I'm not taking it out now, but it works now on my new machine, so that's good enough for now. (If I get the machine back out at some point, I'll plug it into an external monitor and upgrade Rstan to double check.)
